### PR TITLE
Style Footer

### PR DESCRIPTION
**Pull request by calvinmorett**
- change footer background
- change footer & footer button positioning
- add/change footer text styling

style

**Future feature changes**: 
+ Width to be set automatically with viewport calculations. (i.e. 25vw) as well as auto-scaling font-sizing over hard coded pixel values.
+ Also give more spacing between randomize button and artwork-title.

### CODE REVIEW

**Comment by calvinmorett** [comment]
To add more continuity, from the extension and ArtStation, I think it might have been better to design the 'attribution/caption/tool block' aka Footer, as a clone of AS's sidebar view. Reflected these changes in the edit.

**ArtStation Sidebar, for Example:**  
image

Their side bar uses the font, [Open Sans from Google Fonts](https://fonts.google.com/specimen/Open+Sans?sidebar.open=true&selection.family=Open+Sans:wght@300).

This is how the _cloned style_ looks without the Google Fonts; if a user didn't want to load it in.
image

Here is how it looks with the font.
image

_These new changes should reflect the future feature changes, regarding viewport based calculations for the width of the footer. To reflect the style of ArtStation, I used their pixel values._

_More spacing was added, so you wouldn't accidentally click into the Artists art page, visual example below._
image

**Updated Branch, is there anything else I need to do to edit this PR?**

**Comment by winkidney** [comment]
It's awesome idea that combine all information into one card.
But I don't like part of the new design personally. The initial purpose of the design is "hide the information and don't disturb", the new card design will block part of the image in our view.
Would you like to give us an option ( or button) to hide the card (or info) just like the artstation done?
So that, we could view the image as we wish.

Maybe a side-bar design (no block on image view) like artstatoin is a better idea, what do you think about it?

**Comment by calvinmorett** [comment]
Okay let's sort of do a quick test of both ideas

The first one is already done with the hover wrapper view footer, hwvf branch. Where the footer is hidden by default. Example of it in use below, the benefits include.
+ It provides the same experience as before, not obstructing the view of the user if they want to view the artwork, unobstructed, while also providing the attribution for the artist.
+ The location of the buttons are in closer to the top of the page, where you would be creating a new tab, for easier access.

3zeQ4GmuVe

-------------

And here is the full sidebar concept, it's inline w/ cloning ArtStations styling, but the structure or layout or both, would need to be fixed up a little bit more for it to work out correctly. In this quick example the artwork is just set to the opposite side of the sidebar at full 100viewport height. 

H5XkXUYBQ5

-------------

+ I think if the source of the data you're pulling the images/artist info from, if you can get everything ArtStation would show on the actual page, barring some unneeded elements, it would provide a nice experience between the two.

ddPd7XDOEn
⚡⚡⚡⚡⚡

-------------

At the same time with all these ideas, I don't want to detract from the art and the original goal of your project. Please let me know how I can help and what direction you would like to take after seeing these examples.

**Comment by winkidney** [comment]
The current mode is very nice to have : ), I will merge your PR directly, and thanks for your contribution.

**Comment by winkidney** [comment]
I will issue a new release on firefox store.

**Comment by calvinmorett** [comment]
Thank you so much for allowing me to contribute, please let me know if you need me to assist in other ways or on other projects. 

**Action Items for @winkidney:** You will need to add Open Sans to the html, as well. 
`<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">`

**Pull request merged**
